version: "3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: "npm start"
  # ngrok:
  #   image: wernight/ngrok
  #   depends_on:
  #     - app
  #   environment:
  #     - NGROK_DEBUG=1
  #     - NGROK_PORT=app:3000
  #   ports:
  #     - 4040:4040
